{
 "title": "JVM Overview",
 "description": "Dashboard for JVM metrics within Kubernetes, where Prometheus installed using community helm chart",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{app=\"alephium\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app=\"alephium\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{app=\"alephium\"}*1000"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "label_join(jvm_info{app=\"alephium\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=\"alephium\"}[1m]))",
     "measurement": "process_cpu_usage",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "service", "operator": "=~", "value": "/^$service$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{app=\"alephium\"}[1m]))",
     "legendFormat": "process_cpu_usage",
     "query": "from(bucket: \"telegraf\")\n|> range($range)\n|> filter(fn: (r) =>\n  r._measurement == \"process_cpu_usage\" AND\n  r.service == \"$service\" AND\n  r._field == \"gauge\")\n|> keep(columns: [\"_value\", \"_time\", \"_measurement\"])"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{app=\"alephium\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{app=~\"alephium\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Memory area",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{app=\"alephium\"}",
     "legendFormat": "Used {{ area }}"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{ app=\"alephium\"}",
     "legendFormat": "loaded"
    },
    {
     "expr": "jvm_classes_unloaded_total{ app=\"alephium\"}",
     "legendFormat": "unloaded"
    }
   ]
  },
  {
   "title": "Survivor Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "repeat": "mempool",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Survivor Space\", app=\"alephium\"}",
     "legendFormat": "Max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Survivor Space\", app=\"alephium\"}",
     "legendFormat": "Used {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Survivor Space\", app=\"alephium\"}",
     "legendFormat": "Committed {{ pool }}"
    }
   ]
  },
  {
   "title": "Eden Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Eden Space\", app=\"alephium\"}",
     "legendFormat": "Max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Eden Space\", app=\"alephium\"}",
     "legendFormat": "Used {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Eden Space\", app=\"alephium\"}",
     "legendFormat": "Committed {{ pool }}"
    }
   ]
  },
  {
   "title": "Old Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Tenured Gen\", app=\"alephium\"}",
     "legendFormat": "Max {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Tenured Gen\", app=\"alephium\"}",
     "legendFormat": "Used {{ pool }}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{pool=\"Tenured Gen\", app=\"alephium\"}",
     "legendFormat": "Committed {{ pool }}"
    }
   ]
  },
  { "title": "Threads ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Threads State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{app=\"alephium\",state=\"RUNNABLE\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "jvm_threads_state{app=\"alephium\",state=\"BLOCKED\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "jvm_threads_state{app=\"alephium\",state=\"NEW\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "jvm_threads_state{app=\"alephium\",state=\"TERMINATED\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "jvm_threads_state{app=\"alephium\",state=\"TIMED_WAITING\"}",
     "legendFormat": "{{ state }}"
    },
    {
     "expr": "jvm_threads_state{app=\"alephium\",state=\"WAITING\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{app=\"alephium\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{app=\"alephium\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{app=\"alephium\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  }
 ]
}